#!/usr/bin/env python3
"""
Prototype CASE (1EdTech) CFPackage -> draft oe:Competency mapper (RFC-0002
association-type table, RFC-0005 citationOnly mode).

This is a PROTOTYPE. Its output is never valid for merging into
vocabularies/ as-is:
  - IDs are out-of-range placeholders (OE-COMPETENCY-9##### is not a real
    allocated block per GOVERNANCE.md's Identifier Block Allocation table)
    since no RFC has reserved a real block for this source yet.
  - It only processes a small subset of the source package (one
    humanCodingScheme prefix), to keep the demo output reviewable.
  - It does not run scripts/check_related_symmetry.py or otherwise verify
    cross-file consistency.

It always runs the source through scripts/case_license_gate.py first:
  - ALLOW_FULL     -> statement populated from CFItem.fullStatement.
  - CITATION_ONLY  -> RFC-0005 citationOnly entry: humanCodingScheme +
                      provenance only, fullStatement is never copied.
  - BLOCKED        -> refuses to emit anything unless --acknowledge-blocked
                      is passed, since an explicit no-redistribution clause
                      was detected upstream.

Usage:
    python scripts/case_to_competency_prototype.py path/to/CFPackage.json \\
        --prefix "K.AP.1" --out draft-output.yaml [--acknowledge-blocked]
"""

import sys
import json
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from case_license_gate import classify_license, ALLOW_FULL, CITATION_ONLY, BLOCKED  # noqa: E402

PLACEHOLDER_ID_START = 900001


def load_package(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def build_entries(data, prefix, verdict):
    doc = data["CFDocument"]
    items = [
        item for item in data["CFItems"]
        if item.get("humanCodingScheme", "").startswith(prefix)
    ]
    item_by_uuid = {item["identifier"]: item for item in items}
    placeholder_id = {}
    next_num = PLACEHOLDER_ID_START
    for item in items:
        placeholder_id[item["identifier"]] = f"OE-COMPETENCY-{next_num:06d}"
        next_num += 1

    # isChildOf associations within this subset -> skos:broader, per the
    # CASE associationType mapping table in
    # docs/design-notes/case-competency-profile.md.
    broader = {uuid: [] for uuid in item_by_uuid}
    for assoc in data["CFAssociations"]:
        if assoc.get("associationType") != "isChildOf":
            continue
        origin = assoc["originNodeURI"]["identifier"]
        dest = assoc["destinationNodeURI"]["identifier"]
        if origin in item_by_uuid and dest in item_by_uuid:
            broader[origin].append(placeholder_id[dest])

    entries = []
    for item in items:
        uuid = item["identifier"]
        entry = {
            "id": placeholder_id[uuid],
            "type": "oe:Competency",
            "status": "proposed",
            "version": "1.0.0",
            "humanCodingScheme": item.get("humanCodingScheme"),
            "provenance": {
                "sourceCFItemId": uuid,
                "sourceCFItemURI": item.get("uri"),
                "sourceCFDocumentURI": doc.get("uri"),
            },
        }
        if broader[uuid]:
            entry["relations"] = {"skos:broader": broader[uuid]}

        if verdict == ALLOW_FULL:
            entry["statement"] = {"en": item.get("fullStatement", "")}
        else:
            # CITATION_ONLY (BLOCKED is refused before this function runs
            # unless explicitly acknowledged, and even then defaults to
            # the same citationOnly shape).
            entry["citationOnly"] = True

        entries.append(entry)
    return entries, doc


def render_yaml(entries, doc, verdict, source_path):
    import yaml

    header = f"""# ============================================================================
# DRAFT / PROTOTYPE OUTPUT — DO NOT MERGE AS-IS
# ============================================================================
# Generated by scripts/case_to_competency_prototype.py from:
#   {source_path}
# Source CFDocument: {doc.get('title')}
# Source license: {(doc.get('licenseURI') or {}).get('title')}
# License gate verdict: {verdict}
#
# IDs below are out-of-range placeholders (900001+), not a real allocated
# OE-COMPETENCY block (GOVERNANCE.md, Identifier Block Allocation). A real
# ingestion RFC must reserve a block before any of this is merged.
# ============================================================================

"""
    return header + yaml.dump({"competencies": entries}, sort_keys=False, allow_unicode=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("package", help="Path to a CASE CFPackage JSON export")
    parser.add_argument("--prefix", default="", help="Only include CFItems whose humanCodingScheme starts with this prefix")
    parser.add_argument("--out", default=None, help="Output YAML path (default: print to stdout)")
    parser.add_argument("--acknowledge-blocked", action="store_true", help="Proceed with citationOnly output even if the license gate returns BLOCKED (use only after a human has reviewed the source license)")
    args = parser.parse_args()

    data = load_package(args.package)
    doc = data["CFDocument"]
    license_ref = doc.get("licenseURI") or {}
    verdict, reason = classify_license(license_ref.get("title"), license_ref.get("uri"))

    print(f"License gate verdict for {doc.get('title')!r}: {verdict} ({reason})", file=sys.stderr)

    if verdict == BLOCKED and not args.acknowledge_blocked:
        print("Refusing to emit anything: BLOCKED verdict requires --acknowledge-blocked after human review.", file=sys.stderr)
        return 1

    entries, doc = build_entries(data, args.prefix, verdict)
    if not entries:
        print(f"No CFItems matched prefix {args.prefix!r} — nothing to emit.", file=sys.stderr)
        return 1

    output = render_yaml(entries, doc, verdict, args.package)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Wrote {len(entries)} draft entries to {args.out}", file=sys.stderr)
    else:
        print(output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
