#!/usr/bin/env python3
"""RFC-0023: transform openevo-graph's 9 content anchors into
vocabularies/OPENEVO-DESIGN-CONCEPT-v1.0.0.yaml.

Source: ../openevo-graph/nodes/content_anchors.json

Thinking tools are deliberately NOT part of this migration -- they turned
out to already be governed via MethodsBase (6 OE-METHOD-* records added
2026-09-02, see methodsbase/records/methods.yaml), so the "ThinkingTool"
half of the RFC this document's own name-history carries is moot; only
content anchors still needed a home. See RFC-0023 "Motivation".

Each anchor becomes one oe:Concept entry, tagged
extensions["oe:conceptRole"] = "content-anchor" (the same tagged-Concept
pattern RFC-0012 used for eva4k12's cross-cutting themes, rather than a
new ontology class). CASE-standard crosswalk data (caseLinks) is
deliberately not migrated here -- see RFC-0023 "Deferred".

relatedAnchors is carried through exactly as authored, one-directional
where the source is one-directional. Every one of the 9 source anchors
lists exactly 3 relatedAnchors, no more and no fewer -- a deliberate
curated "top 3" per anchor, not an authoring gap, confirmed by checking
the source data directly. An earlier draft of this script auto-added
reciprocal edges to satisfy skos:related's SKOS-spec symmetry, which
would have pushed 7 of the 9 anchors to 4 relations each, silently
overriding that curation. scripts/check_related_symmetry.py will
correctly report this vocabulary as asymmetric -- expected and accepted,
not a bug to fix. See RFC-0023 "Proposed change".

Run from the conceptbase repo root: python scripts/migrate_content_anchors.py
"""
import json
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT.parent / "openevo-graph" / "nodes" / "content_anchors.json"
OUT_PATH = REPO_ROOT / "vocabularies" / "OPENEVO-DESIGN-CONCEPT-v1.0.0.yaml"

VOCAB_SLUG = "openevo-design-concept"


def load_source():
    with open(SOURCE_PATH, encoding="utf-8") as f:
        return json.load(f)


def concept_id(anchor_id: str) -> str:
    return f"OE-CONCEPT-{VOCAB_SLUG}-{anchor_id}"


def build_entry(node: dict) -> dict:
    entry = {
        "id": concept_id(node["id"]),
        "type": "oe:Concept",
        "status": "proposed",
        "version": "1.0.0",
        "definedInVocabulary": "OPENEVO-DESIGN-CONCEPT-v1.0.0",
        "labels": {"en": node["label"]},
        "definitions": {"en": {"general": node["coreIdea"].strip()}},
    }

    related = node.get("relatedAnchors") or []
    if related:
        entry["relations"] = {
            "skos:related": [concept_id(rid) for rid in related]
        }

    entry["extensions"] = {
        "oe:conceptRole": "content-anchor",
        "oe:discipline": node["discipline"],
        "oe:subjectAreas": node.get("subjectAreas", []),
        "oe:developmentalArc": node["gradeProgression"],
        "oe:fullDescription": node["desc"].strip(),
    }
    if node.get("tags"):
        entry["extensions"]["oe:tags"] = node["tags"]
    if node.get("note"):
        entry["extensions"]["oe:curatorNote"] = node["note"].strip()

    return entry


def main():
    source = load_source()
    entries = [build_entry(n) for n in source["nodes"]]

    header = f"""\
# ============================================================================
# OpenEvo ConceptBase -- Controlled Vocabulary: OPENEVO-DESIGN-CONCEPT
# ============================================================================
# Path: /vocabularies/OPENEVO-DESIGN-CONCEPT-v1.0.0.yaml
#
# The 9 OpenEvo content anchors (Ancient Ancestors, Cross-species
# Comparisons, Child Development, Cooperation Games, Cultural Diversity,
# Governing the Commons, Our Mind, Computer Models, Global Sustainability
# Goals) -- the foundational disciplinary entry points OpenEvo's
# curriculum-design concept is organized around. Migrated per RFC-0023
# from openevo-graph/nodes/content_anchors.json, the only prior
# machine-readable copy of this vocabulary and now a generated mirror of
# this file. Generated by scripts/migrate_content_anchors.py -- do not
# hand-edit content sourced from there without also updating the source
# JSON for provenance consistency.
#
# Each anchor is a tagged oe:Concept (extensions["oe:conceptRole"] =
# "content-anchor"), not a new ontology class -- see RFC-0023 "Standards
# justification". Grade-band progressions (K-2 through 13-16) have no
# matching schema field and are carried losslessly via
# extensions["oe:developmentalArc"], the same field name and pattern
# RFC-0012 established for eva4k12's own developmental-arc content.
#
# The 6 OpenEvo thinking tools are NOT part of this vocabulary -- they
# already have a governed home as oe:Method records in MethodsBase
# (methodsbase/records/methods.yaml, OE-METHOD-tinbergens-questions and
# five siblings, added 2026-09-02). See RFC-0023 "Motivation".
#
# CASE-standard crosswalk data (NGSS/C3/IB MYP/etc. alignments) is
# deliberately not migrated here -- see RFC-0023 "Deferred". It stays in
# openevo-graph/nodes/content_anchors.json until a later RFC gives it a
# ConceptBase home (Phase 2 alignments).
#
# relatedAnchors is carried through exactly as authored -- every anchor has
# exactly 3, a deliberate curation, not always reciprocal. This intentionally
# does NOT satisfy scripts/check_related_symmetry.py's symmetry expectation;
# that check is advisory (not run in CI, see .github/workflows/validate.yml),
# and forcing symmetry here would override the source's own top-3 curation.
# See RFC-0023 "Proposed change".
# ============================================================================

meta:
  id: OPENEVO-DESIGN-CONCEPT
  version: 1.0.0
  status: proposed
  scope: >
    The 9 content anchors of OpenEvo's educational design concept --
    the foundational, cross-disciplinary phenomenological entry points
    (alongside the 3 design principles and 6 thinking tools, the latter
    governed separately in MethodsBase) that OpenEvo curriculum design is
    organized around.
  discipline: interdisciplinary
  license: CC-BY-NC-SA-4.0
  authors:
    - name: OpenEvo ConceptBase Maintainers
  conformsTo: OE-SCHEMA-CONCEPT-v1.2.0
  phase: 1

concepts:
"""

    body = yaml.safe_dump(entries, sort_keys=False, allow_unicode=True, width=88)
    indented = "\n".join(
        ("  " + line if line.strip() else line) for line in body.splitlines()
    )

    OUT_PATH.write_text(header + indented + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
