// Builds ConceptBase-conformant YAML from the user's in-browser annotations
// and alignment drafts, so exploration/tagging work done on the static site
// can be turned into a real RFC contribution (spec §11.2) back to a
// dependent repository or to conceptbase/alignments/.
//
// Two export shapes, matching the two places the spec provides an explicit
// escape hatch:
//  - Alignment drafts -> documents conforming to alignment.schema.yaml
//    (§9.1), with a locally-generated draft id in the reserved 9xxxxx range
//    and a header comment noting it must be reassigned during RFC review.
//  - Free-form tags/notes/evidence on any entity -> an `extensions` patch
//    (§7.4) namespaced under `oe:userAnnotation`, since core schemas forbid
//    additional top-level properties (additionalProperties: false) and this
//    is the spec's designated forward-compatible attachment point.

import { toYaml } from "./yaml.js";
import { hashToSixDigits, todayIso } from "./utils.js";

export function draftAlignmentId(subjectRef, objectRef, createdAt) {
  return `OE-ALIGN-${hashToSixDigits(subjectRef + "|" + objectRef + "|" + createdAt)}`;
}

export function buildAlignmentRecord(draft) {
  return {
    id: draftAlignmentId(draft.subjectRef, draft.objectRef, draft.createdAt),
    subject: draft.subjectRef,
    object: draft.objectRef,
    matchType: draft.matchType,
    assertedBy: [draft.assertedBy || "Anonymous ConceptBase Explorer user"],
    date: draft.date || todayIso(),
    status: draft.status || "proposed",
    rationale: draft.rationale || "",
  };
}

export function exportAlignmentDraftsYaml(drafts) {
  if (!drafts.length) return "# No alignment drafts to export.\n";
  const header = [
    "# ============================================================================",
    "# DRAFT cross-vocabulary alignment records — generated by the ConceptBase",
    "# Explorer app (not an official registry submission).",
    "#",
    "# Each `id` below is a locally-generated placeholder in the unassigned",
    "# 9xxxxx range and MUST be reassigned by a maintainer during RFC review",
    "# before merge into /alignments/ (see docs/oecb_specifications.md §9, §11.2).",
    "# Submit these as a pull request against /proposals/ per GOVERNANCE.md.",
    "# ============================================================================",
    "",
  ].join("\n");
  const docs = drafts.map((d) => toYaml(buildAlignmentRecord(d)));
  return header + docs.join("\n---\n\n");
}

export function buildAnnotationExtensionPatch(note) {
  return {
    entityId: note.entityId,
    entityType: note.entityType,
    entityLabel: note.entityLabel,
    slot: note.slot,
    extensions: {
      "oe:userAnnotation": {
        tags: note.tags || [],
        note: note.note || "",
        evidence: (note.evidence || []).map((e) => ({ text: e.text, url: e.url || undefined, doi: e.doi || undefined })),
        author: note.author || undefined,
        createdAt: note.createdAt,
        updatedAt: note.updatedAt,
      },
    },
  };
}

export function exportNotesYaml(notes) {
  if (!notes.length) return "# No annotations to export.\n";
  const header = [
    "# ============================================================================",
    "# User annotations — generated by the ConceptBase Explorer app.",
    "#",
    "# Each entry patches the named entity's `extensions` block (schemas' open,",
    "# namespaced escape hatch, see docs/oecb_specifications.md §7.4) under the",
    "# `oe:userAnnotation` key. These are NOT auto-merged into any source file —",
    "# a maintainer/contributor should fold the relevant `extensions` value into",
    "# the actual entity YAML by hand (or via RFC, if the tag/evidence should",
    "# become part of the canonical record).",
    "# ============================================================================",
    "",
  ].join("\n");
  const docs = notes.map((n) => toYaml(buildAnnotationExtensionPatch(n)));
  return header + docs.join("\n---\n\n");
}

export function exportFullBackupYaml(data) {
  const header = [
    "# ConceptBase Explorer — full annotation backup.",
    "# Re-import this file from the Annotations tab to restore your work.",
    "",
  ].join("\n");
  return header + toYaml(data);
}
